<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net8.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser"/>
        <PackageReference Include="IconPacks.Avalonia" />
        <PackageReference Include="Irihi.Ursa" />
        <PackageReference Include="Irihi.Ursa.Themes.Semi" />
        <PackageReference Include="SpacedGrid-Avalonia" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\QCMaster\QCMaster.csproj"/>
    </ItemGroup>
</Project>
